repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --ignore, F401]

-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      -   id: black
