version: '3.8'

services:
  web:
    build: ./src
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./src/.env
    depends_on:
      pgdb:
        condition: service_healthy
        restart: true
        

  pgdb:
    image: postgres:15.4-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=simple_django
      - POSTGRES_PASSWORD=simple_django
      - POSTGRES_DB=django_dev
    container_name: pgdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: