services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile.dev
    container_name: dating_app_web
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./src/.dev.env
    depends_on:
      pgdb:
        condition: service_healthy
        restart: true

  pgdb:
    image: postgres:17.0-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: dating_app_pgdb
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10m
      timeout: 3s
      retries: 5
      start_period: 15s
    env_file:
      - ./src/db.dev.env

  nginx:
    image: nginx:1.27-alpine
    container_name: dating_app_nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static  # Статика из Django
      - media_volume:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Конфиг Nginx
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
