services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: django
    command: bash -c "python manage.py migrate &&
                      python manage.py collectstatic --noinput &&
                      gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - ./src/:/usr/src/app
      - static_volume:/usr/src/app/static # separate static files with project volume
    ports:
      - 8001:8000
    env_file:
      - ./src/.env
    depends_on:
      pgdb:
        condition: service_healthy
        restart: true


  pgdb:
    image: postgres:17.0-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: pgdb
    ports:
      - 54320:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 3s
      retries: 5
    env_file:
      - ./src/db.env


volumes:
  postgres_data:
  static_volume: