services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: django
    command: bash -c "python manage.py migrate &&
                      python manage.py collectstatic --noinput &&
                      gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - ./src/:/usr/src/app
      - static_volume:/usr/src/app/static # separate static files with project volume
    # ports:
      # - 8001:8000
    expose:
      - 8000
    env_file:
      - ./src/.env
    depends_on:
      pgdb:
        condition: service_healthy
        restart: true


  pgdb:
    image: postgres:17.0-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: pgdb
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10m
      timeout: 3s
      retries: 5
      start_period: 15s
      start_interval: 5s
    env_file:
      - ./src/db.env

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/app/static  # Статика из Django
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Конфиг Nginx
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: