FROM python:3.12.9-slim-bookworm

ENV PATH="/venv/bin:$PATH" \
    UV_PROJECT_ENVIRONMENT="/venv" \
    PYTHONUNBUFFERED=1

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.6.3 /uv /uvx /usr/local/bin/

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --link-mode=copy

COPY . /app/

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen

CMD bash -c "python manage.py migrate && \
    python manage.py collectstatic --noinput && \
    gunicorn --bind 0.0.0.0:8000 config.wsgi:application"