name: Lint, typechecking and tests

on: [push, pull_request]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v4
    - name: Install Python 3.11
      uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
    - name: Install dependecies
      working-dirrectory: ./api
      run: |
        python -m pip install --upgrade  pip
        pip install -r requirements.txt
        pip install black flake8
      
    - name: Check code formating by Black
      working-dirrectory: ./api
      run: |
        python -m black .
    
    - name: Lint code by flake8
      working-dirrectory: ./api
      run: |
        python -m flake8 --exclude venv --ignore=E501,F401

    - name: Run tests
      working-dirrectory: ./api
      run: | 
        python manage.py tests