name: Lint, typechecking and tests

on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Python 3.12.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.9'
      
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install project
      working-directory: src
      run: uv sync --all-extras --dev  
    
    - name: Check code formating by Black
      working-directory: src
      run: uv run black . --check
    
    - name: Lint code by ruff
      working-directory: src
      run: uv run ruff check . --ignore F401

    - name: Run tests
      working-directory: src
      run: uv run manage.py test