name: Lint, typechecking and tests

on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
        
    - name: Install dependecies
      working-directory: src
      run: |
        python -m pip install --upgrade  pip
        pip install -r requirements.test.txt
      
    - name: Check code formating by Black
      working-directory: src
      run: |
        python -m black . --check
    
    - name: Lint code by ruff
      working-directory: src
      run: |
        python -m ruff check .

    - name: Run tests
      working-directory: src
      run: | 
        python manage.py test